#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 04 22:01:16 2016
@author: David
"""

# Dictionary module

def pngNames():    # return dictionary
    return {'SIS' : 'sisters by Marie Van den Broeck from Noun Project',
            'SIR' : 'sir by Oliviu Stoian from Noun Project',
            'SIP' : 'Drink by Jhun Capaya from Noun Project',
            'SIT' : 'Directors Chair by Dara Ullrich from Noun Project',
            'NYS' : 'New York by Maria Darron from Noun Project',
            'AGE' : 'Life Stage by Jeff Gerlach from Noun Project',
            'SIX' : 'Six by Jonathan Li from Noun Project',
            'SIC' : 'Quotation Marks by Louis Buck from Noun Project',
            'YUM' : 'yum by Arkthus from Noun Project',
            'SIN' : 'Garden of Eden by Bruno Gatjens Gonzalez from Noun Project',
            'SIM' : 'SIM Card by Rohan Gupta from Noun Project',
            'NYE' : 'New Year\'s Day by Amos Meron from Noun Project',
            'TAT' : 'Tattoo Machine by Eric Bergholz from Noun Project',
            'SPY' : 'spy by Dan Hetteix from Noun Project',
            'TAP' : 'tap by P.J. Onori from Noun Project',
            'TAR' : 'Photo by Richard Schumann from Noun Project',
            'TAX' : 'tax by Juan Pablo Bravo from Noun Project',
            'OBS' : 'warning sign by Alv Jorgen Bovolden from Noun Project',
            'TAD' : 'Baby by 23 icons from Noun Project',
            'TAG' : 'Tag by John Caserta from Noun Project',
            'TAB' : 'tab by Julien Deveaux from Noun Project',
            'YUP' : 'Happy by Pham Thi Dieu Linh from Noun Project',
            'SPA' : 'spa by Amelia Wattenberger from Noun Project',
            'TAN' : 'Tanning Bed by Michal Kaminski from Noun Project',
            'TAO' : 'taoism by Valerio Poltrini from Noun Project',
            'TAJ' : 'Taj Mahal by hunotika from Noun Project',
            'TAK' : 'talk by Cameron Wishart from Noun Project',
            'JIG' : 'Dancing by Edward Boatman from Noun Project',
            'GIT' : 'alien by Mister Pixel from Noun Project',
            'GIS' : 'GIS by Iconathon from Noun Project',
            'GIG' : 'music venue by Vicons Design from Noun Project',
            'GIF' : 'gif by Makhmudkhon from Noun Project',
            'GO' : 'go by athanagore x from Noun Project',
            'GIN' : 'gin by Alvaro Molero from Noun Project',
            'BYE' : 'Hand by Vlad Likh from Noun Project',
            'MAP' : 'Map by DEADTYPE from Noun Project',
            'MAS' : 'Plus by Javier Cabezas from Noun Project',
            'MAR' : 'Anchor by Noe Araujo from Noun Project',
            'MAT' : 'carpet by Gabriella Cinque from Noun Project',
            'MAY' : 'Melolontha by Arthur Shlain from Noun Project',
            'MAX' : 'Settings by Juan Pablo Bravo from Noun Project',
            'RUM' : 'Rum by Geoffrey Joe from Noun Project',
            'MAA' : 'maternity by Pratyush Das from Noun Project',
            'MAC' : 'mac by Umar Irshad from Noun Project',
            'MAD' : 'Mad by Mike Ashley from Noun Project',
            'MAG' : 'Magnifying Glass by David Papworth from Noun Project',
            'MAM' : 'Woman by Cristiano Zoucas from Noun Project',
            'MAL' : 'beard by Jose Manuel de Laa from Noun Project',
            'MAN' : 'Man from Noun Project',
            'BEN' : 'ben by Ari Junior from Noun Project',
            'BEL' : 'Alarm by Vicons Design from Noun Project',
            'EVO' : 'Mercedes E190 Evoluzione by Andrea Severgnini from Noun Project',
            'BEG' : 'Pleading by James Keuning from Noun Project',
            'BED' : 'Bed by Christopher T. Howlett from Noun Project',
            'BEE' : 'bee by Juan Sebastian Rickenmann from Noun Project',
            'GUT' : 'Stomach by Jamie Dickinson from Noun Project',
            'GUY' : 'guy by Tommy Lau from Noun Project',
            'BET' : 'mobile payment by Adam  Mullin from Noun Project',
            'HUD' : 'Pilot Helmet by Henry Ryder from Noun Project',
            'HUE' : 'Venn Diagram by Ben Rex Furneaux from Noun Project',
            'LSD' : 'Psyche Eye by Lucas Rod from Noun Project',
            'HUG' : 'hug by Veysel Kara from Noun Project',
            'HUB' : 'hub by iconsmind.com from Noun Project',
            'HUM' : 'hum by Alberto Miranda from Noun Project',
            'HUN' : 'Hungary flag by Valerio Poltrini from Noun Project',
            'HUH' : 'huh by Alfredo Hernandez from Noun Project',
            'HUT' : 'Hut by artworkbean from Noun Project',
            'ED' : 'Impotent by Stephen Plaster from Noun Project',
            'NOM' : 'eating by Blaise Sewell from Noun Project',
            'NON' : 'No by Rohan Gupta from Noun Project',
            'NOD' : 'Ring by Siddharth Dasari from Noun Project',
            'NOG' : 'eggnog by Cards Against Humanity from Noun Project',
            'NOB' : 'Gauge by Rohith M S from Noun Project',
            'NOT' : 'Minus by Arthur Shlain from Noun Project',
            'NOW' : 'Real Time Data by Jerad Maplethorpe from Noun Project',
            'NOR' : 'Nor by Marco Olgio from Noun Project',
            'NOS' : 'Oxygen Tank by Spicy Icons from Noun Project',
            'REX' : 'Tyranosaurus by Dactrtr from Noun Project',
            'REP' : 'representative by Sara Jeffries from Noun Project',
            'REW' : 'rew by Herbert Spencer from Noun Project',
            'REM' : 'sleeping by john melven from Noun Project',
            'REC' : 'Rec by Herbert Spencer from Noun Project',
            'REF' : 'touchdown by Darrin Higgins from Noun Project',
            'RED' : 'red by Raul Santos from Noun Project',
            'WHA' : 'Wha? by Alfredo Hernandez from Noun Project',
            'WHO' : 'Dalek by Nate Holland from Noun Project',
            'OUD' : 'Oud by Mohamad Sabbagh from Noun Project',
            'AIT' : 'Air Fryer by Franco De Felice from Noun Project',
            'OUR' : 'Basement by Juan Pablo Bravo from Noun Project',
            'WHY' : 'Why?! by eivven from Noun Project',
            'OUT' : 'Out by James Keuning from Noun Project',
            'VET' : 'vet by Asier Bilbo from Noun Project',
            'YIN' : 'Ying Yang by Piotr Gawinski from Noun Project',
            'VEG' : 'delivery by Claire Jones from Noun Project',
            'VEE' : 'down by Pencil from Noun Project',
            'TAM' : 'graduate by Luis Prado from Noun Project',
            'SI' : 'width by Magicon from Noun Project',
            'SH' : 'Calavera by Simon Child from Noun Project',
            'SO' : 'Acorn by anbileru adaleru from Noun Project',
            'ORE' : 'Ore by Callum Taylor from Noun Project',
            'ORB' : 'Eye by Shmidt Sergey from Noun Project',
            'ORC' : 'Orc by Rodrigo Vidinich from Noun Project',
            'ORA' : 'incorrect by Daniel Nochta from Noun Project',
            'CAY' : 'Turkish Tea by Omer Faruk AYRANCI from Noun Project',
            'CAR' : 'Car from Noun Project',
            'CAP' : 'Cap by Olivier Guin from Noun Project',
            'CAW' : 'Bird by Kemesh Maharjan from Noun Project',
            'CAT' : 'Cat by Marie Coons from Noun Project',
            'CAN' : 'can by Megan Strickland from Noun Project',
            'CAM' : 'cam by Chameleon Design from Noun Project',
            'CAB' : 'Cab by Creative Stall from Noun Project',
            'UKE' : 'ukulele by Angela Gasparetti from Noun Project',
            'CAD' : 'cad by Jose Sanmartin Gonzalez from Noun Project',
            'LA' : 'Day Fog by Gregory Sujkowski from Noun Project',
            'LI' : 'list view by Nathan Chase from Noun Project',
            'DYE' : 'Paint Brush by Christopher T. Howlett from Noun Project',
            'UP' : 'up by John Chapman from Noun Project',
            'FAR' : 'Telescope Spy by Till Teenck from Noun Project',
            'MIM' : 'MIM File by Arthur Shlain from Noun Project',
            'MIL' : 'Mil by Yu luck from Noun Project',
            'SOM' : 'Left Speaker by Halfazebra Studio from Noun Project',
            'MIC' : 'mic by Anusha Narvekar from Noun Project',
            'MIB' : 'Neuralyzer by Jonas Nullens from Noun Project',
            'MID' : 'music-file by Arthur Shlain from Noun Project',
            'MIG' : 'Beer by Dominique Vicent from Noun Project',
            'GUN' : 'Gun by Edward Boatman from Noun Project',
            'GIO' : 'Gio by tatiemi iwamoto from Noun Project',
            'BE' : 'Be by athanagore x from Noun Project',
            'MIS' : 'Headset by Gilad Sotil from Noun Project',
            'MIR' : 'Rocket by Zoran Djordjijevic from Noun Project',
            'SAI' : 'Sai by Yevgeniy Osovets from Noun Project',
            'JOT' : 'Writing by Korokoro from Noun Project',
            'SAN' : 'San Siro Stadium by luca orlandini from Noun Project',
            'SAM' : 'Uncle Sam by Luis Prado from Noun Project',
            'SAL' : 'sal by Clockwise from Noun Project',
            'SAC' : 'In a Bubble by Luis Prado from Noun Project',
            'SAB' : 'Speaker by 23 icons from Noun Project',
            'PRO' : 'Laptop by MaxineVSG from Noun Project',
            'SAG' : 'arrows by Joao Proenca from Noun Project',
            'GAM' : 'Puzzle by Eric M. Ellis from Noun Project',
            'SAD' : 'Sad from Noun Project',
            'SAY' : 'say by Herbert Spencer from Noun Project',
            'SAX' : 'Saxophone by Hum from Noun Project',
            'VAT' : 'bucket by Richard Schumann from Noun Project',
            'JOG' : 'Running by Michael Scott Fischer from Noun Project',
            'SAP' : 'Butterfly by Shawn Wong from Noun Project',
            'SAW' : 'saw by John Bruggemann from Noun Project',
            'SAV' : 'Telephone Operator by Samy Menai from Noun Project',
            'SAT' : 'Satellite by Anton Kovalev from Noun Project',
            'ZIT' : 'Acne by Luis Prado from Noun Project',
            'CHE' : 'Garlic by Catherine Please from Noun Project',
            'URB' : 'skyline by isaac claramunt from Noun Project',
            'JAY' : 'Bird by MarkieAnn Packer from Noun Project',
            'JAW' : 'Skull and Crossbones by Luis Prado from Noun Project',
            'URN' : 'urn by Jorge Carrillo from Noun Project',
            'JAR' : 'Jar by Giulio Bertolotti from Noun Project',
            'ZIG' : 'doodle by Kyle Tezak from Noun Project',
            'JAM' : 'Jam by Joe Harrison from Noun Project',
            'JAK' : 'Kettle by Aldric Rodriguez Iborra from Noun Project',
            'JAG' : 'Kettle by Aldric Rodriguez Iborra from Noun Project',
            'JAB' : 'boxer by Anton Håkanson from Noun Project',
            'APP' : 'App by Garrett Knoll from Noun Project',
            'MUG' : 'mug by The Crew at Fusionary from Noun Project',
            'APT' : 'building by Sarah JOY from Noun Project',
            'APE' : 'ape by Milky - Digital innovation from Noun Project',
            'AHI' : 'Sushi by Bradley Ashburn from Noun Project',
            'HMM' : 'hmm by Alfredo Hernandez from Noun Project',
            'OVA' : 'ovary by Leszek Pietrzak from Noun Project',
            'BMW' : 'Motorcycle by Bernd Poethen from Noun Project',
            'EM' : 'Em Chord by Fabio Granara from Noun Project',
            'EL' : 'Subway by jaap from Noun Project',
            'EN' : 'File by Chameleon Design from Noun Project',
            'EH' : 'bored by Pham Thi Dieu Linh from Noun Project',
            'SHY' : 'Shy by Erin Standley from Noun Project',
            'ASP' : 'Snake by Sergey Demushkin from Noun Project',
            'SHE' : 'girl by Rafael Farias Leao from Noun Project',
            'SHH' : 'Quiet Space by Iconathon from Noun Project',
            'ET' : 'E.T. by Vincent Autin from Noun Project',
            'ES' : 'Light Bulb by Eliricon from Noun Project',
            'ER' : 'Hospital by David Scarna from Noun Project',
            'LUV' : 'Utility Vehicle by Luis Prado from Noun Project',
            'LUX' : 'Limousine by Yi Chen from Noun Project',
            'LUZ' : 'lamp by Rafael Farias Leao from Noun Project',
            'LUG' : 'Lungs by Yazmin Alanis from Noun Project',
            'ECO' : 'eco by Alex Kwa from Noun Project',
            'ID' : 'id by Dys Sahagun from Noun Project',
            'ECU' : 'Shield by Jeremy Esnault from Noun Project',
            'XI' : 'Danger by Yohann Berger from Noun Project',
            'YAY' : 'Happy by Tina Abi Hachem from Noun Project',
            'YAW' : 'yaw by Jon from Noun Project',
            'BBC' : 'rapper by Amos Kofi Commey from Noun Project',
            'EVE' : 'Garden of Eden by Bruno Gatjens Gonzalez from Noun Project',
            'YAM' : 'yam by Chen Sizhao from Noun Project',
            'GUM' : 'gum by Alex De Stasio from Noun Project',
            'YAK' : 'chat by Miso Duzek from Noun Project',
            'YAD' : 'Yad by Alessandra Botto from Noun Project',
            'TSA' : 'Razor Blade by Evan MacDonald from Noun Project',
            'TUX' : 'Bow Tie by Chris McDonnell from Noun Project',
            'KEN' : 'Kendama by Bradley Ashburn from Noun Project',
            'KEG' : 'keg by Tyler DeHague from Noun Project',
            'KED' : 'Sneaker by icon 54 from Noun Project',
            'TUT' : 'tomb by Vectors Market from Noun Project',
            'TUI' : 'Tui by Nicole Macdonald from Noun Project',
            'TUM' : 'Wrench by Alex Bu from Noun Project',
            'KEY' : 'Key by Edward Boatman from Noun Project',
            'TUB' : 'tub by Demarque Toi from Noun Project',
            'TUG' : 'pull by Luis Prado from Noun Project',
            'EX' : 'Heart by Martha Ormiston from Noun Project',
            'ASS' : 'Donkey by giulia from Noun Project',
            'POW' : 'pow by ludovic gicqueau from Noun Project',
            'POT' : 'pot by factor[e] design initiative from Noun Project',
            'POS' : 'POS by Oliviu Stoian from Noun Project',
            'POP' : 'pop by Huu Nguyen from Noun Project',
            'POO' : 'poo by WARPAINT Media Inc. from Noun Project',
            'POM' : 'Pomegranate by Creative Stall from Noun Project',
            'POH' : 'Panda by Jolan Soens from Noun Project',
            'POI' : 'poi by Alex Tai from Noun Project',
            'POD' : 'Bean by Elves Sousa from Noun Project',
            'DUD' : 'blind date by Marie Van den Broeck from Noun Project',
            'YAR' : 'Time service by Aha-Soft from Noun Project',
            'QT' : 'Video by Richard Schumann from Noun Project',
            'QI' : 'aura by Andrew Forrester from Noun Project',
            'PAP' : 'rice by Arthur Shlain from Noun Project',
            'PAR' : 'Golf Tee by Erik Wagner from Noun Project',
            'PAT' : 'Pet by Cristiano Zoucas from Noun Project',
            'PAV' : 'Missal Pav by Adil Siddiqui from Noun Project',
            'PAW' : 'Paw by Ben Hsu from Noun Project',
            'PAX' : 'Fast Food by Cards Against Humanity from Noun Project',
            'PAY' : 'pay by Alex Auda Samora from Noun Project',
            'PAC' : 'pac by Iconathon from Noun Project',
            'PAD' : 'pad by Ashley Fiveash from Noun Project',
            'AXE' : 'Axe by George T Hayes from Noun Project',
            'NIB' : 'nib by Isabel Martinez Isabel from Noun Project',
            'PAL' : 'Couple by Luis Prado from Noun Project',
            'PAN' : 'Pan by Edward Boatman from Noun Project',
            'BA' : 'Mortarboard by Alex Bu from Noun Project',
            'AWN' : 'grass by Colleen Wilson from Noun Project',
            'AWL' : 'Awl by Gemma Garner from Noun Project',
            'AWE' : 'Awe by Elena Rimeikaite from Noun Project',
            'WEB' : 'web by Consumer Financial Protection Bureau from Noun Project',
            'OFF' : 'off by Arthur Shlain from Noun Project',
            'WEE' : 'slide by Jamil Ramirez from Noun Project',
            'WED' : 'wedding by Emily Keller from Noun Project',
            'NAN' : 'Sad Grandparents by Cezary Lopacinski from Noun Project',
            'WET' : 'Umbrella by Okan Benn from Noun Project',
            'PHI' : 'Phi by Jasmine Jones from Noun Project',
            'OIL' : 'Oil by Edward Boatman from Noun Project',
            'PHO' : 'Beef Noodle Soup by Bradley Ashburn from Noun Project',
            'ZAG' : 'Zag by Stephen Plaster from Noun Project',
            'TIN' : 'tin by S. Salinas from Noun Project',
            'TUP' : 'Coffee by NIXX from Noun Project',
            'ZAP' : 'Lightning by Thomas Le Bas from Noun Project',
            'SKY' : 'sky by anbileru adaleru from Noun Project',
            'SKA' : 'Dancing by Jack from Noun Project',
            'TIE' : 'Tie by Edward Boatman from Noun Project',
            'SKI' : 'Ski by Anna Weiss from Noun Project',
            'GER' : 'Ger by Laurens from Noun Project',
            'BUY' : 'buy by Sebastian Wiercinski from Noun Project',
            'JUG' : 'jug by Ashley Kolodziej from Noun Project',
            'GET' : 'Trust Fall by Juan Pablo Bravo from Noun Project',
            'BUR' : 'Fire by Mike Ashley from Noun Project',
            'BUS' : 'Bus from Noun Project',
            'BUT' : 'Wrench by Gregory Sujkowski from Noun Project',
            'JUS' : 'Law by Arthur Shlain from Noun Project',
            'BUN' : 'bun by kelsey prinz from Noun Project',
            'JUT' : 'Clamp by Andreas Rottem from Noun Project',
            'GED' : 'GED File by Viktor Vorobyev from Noun Project',
            'EPA' : 'Outfall by Luis Prado from Noun Project',
            'GEO' : 'Location by Arthur Schmitt from Noun Project',
            'BUG' : 'Bug by Edward Boatman from Noun Project',
            'BUD' : 'Sinking Mud by Luis Prado from Noun Project',
            'GEL' : 'Airtanker by Luis Prado from Noun Project',
            'TUN' : 'Barrel by Ted Casper from Noun Project',
            'ZOO' : 'Zoo by Vicons Design from Noun Project',
            'AND' : 'and by Nathan David Smith from Noun Project',
            'PSI' : 'Psi by Jasmine Jones from Noun Project',
            'ANN' : 'Rag Doll by Arancha R from Noun Project',
            'MOP' : 'Mop by Shelagh McLellan from Noun Project',
            'MOW' : 'grass by Tim Shedor from Noun Project',
            'ANT' : 'Ant by Jacob Eckert from Noun Project',
            'MOO' : 'Cow by Alessandro Costa from Noun Project',
            'MON' : 'Cloudy Night by Kirill Tomilov from Noun Project',
            'MOM' : 'Mom by Tomek Woloszyn from Noun Project',
            'MOB' : 'broom by Anna Weiss from Noun Project',
            'MOG' : 'Roomba Cat by Theresa Stoodley from Noun Project',
            'ANY' : 'Grab Any Opportunity by N.K.Narasimhan from Noun Project',
            'PST' : 'Pst File by anbileru adaleru from Noun Project',
            'MOD' : 'Mod Roundel by Andrew Cameron from Noun Project',
            'TIC' : 'Tic Tac Toe by Adam  Mullin from Noun Project',
            'ETA' : 'arrival by Pham Thi Dieu Linh from Noun Project',
            'ETH' : 'Eth Zurich-Swiss Federal Institute Of Technology by NATAPON CHANTABUTR from Noun Project',
            'HEW' : 'Axe by Arthur Shlain from Noun Project',
            'HER' : 'girl by Ji Sub Jeong from Noun Project',
            'SRI' : 'shri by Vaibhav Sawant from Noun Project',
            'HEX' : 'hex by Lazaros Abraxus from Noun Project',
            'HEY' : 'Yo by Matt Brooks from Noun Project',
            'HEM' : 'Needle and Thread by Jose Manuel de Laa from Noun Project',
            'HEN' : 'hen by Iain Hector from Noun Project',
            'CU' : 'Copper by Alejandro Dorantes from Noun Project',
            'GAP' : 'gap by Michael Senkow from Noun Project',
            'LOB' : 'Runner by Adriano Emerick from Noun Project',
            'LOG' : 'log by Arthur Schmitt from Noun Project',
            'LOO' : 'Toilet by Luis Prado from Noun Project',
            'LOL' : 'lol by Gareth from Noun Project',
            'LOW' : 'Battery by P.J. Onori from Noun Project',
            'LOT' : 'Land For Sale by Jorge Calvo Garcia from Noun Project',
            'LOU' : 'Ice Bucket Challenge by Matt Brooks from Noun Project',
            'OWL' : 'Owl by Cedric Stephane Touati from Noun Project',
            'FAX' : 'fax by OCHA Visual Information Unit from Noun Project',
            'OWN' : 'Lion by Van Burn from Noun Project',
            'OWE' : 'Credit Card by Martha Ormiston from Noun Project',
            'FAP' : 'Lotion by Lee Nathan from Noun Project',
            'FAQ' : 'FAQ by Alice Mortaro from Noun Project',
            'FAT' : 'Obesity by James Stone from Noun Project',
            'GAN' : 'Fan by Vandita Malhodra from Noun Project',
            'FAN' : 'Fan by Edward Boatman from Noun Project',
            'FAB' : 'Popsicle by Grace Mitchell from Noun Project',
            'FAA' : 'Drone by Rohith M S from Noun Project',
            'FAG' : 'No Smoking by James Cottell from Noun Project',
            'FAD' : 'fashion by Vicons Design from Noun Project',
            'FAE' : 'Skull by Wayne Tyler Sall from Noun Project',
            'YOU' : 'User by Naomi Atkinson from Noun Project',
            'EBB' : 'High Tide by Luis Prado from Noun Project',
            'BID' : 'Math by OliM from Noun Project',
            'DRY' : 'Dry by iconsmind.com from Noun Project',
            'OAK' : 'oak by lastspark from Noun Project',
            'OAT' : 'Trawler by Guillaume Kurkdjian from Noun Project',
            'OAR' : 'oar by Franck Juncker / fjopus7 from Noun Project',
            'FU' : 'Middle Finger by Piotrek Chuchla from Noun Project',
            'OHM' : 'om by Cedric Villain from Noun Project',
            'PIN' : 'Pin by KB from Noun Project',
            'PIC' : 'Photo Gallery by Antar from Noun Project',
            'IOS' : 'iOS by factor[e] design initiative from Noun Project',
            'PIE' : 'Pie by Bram van Rijen from Noun Project',
            'PIG' : 'Pig by Karen Henderson from Noun Project',
            'PIX' : 'Camera by Kelig Le Luron from Noun Project',
            'ION' : 'ion by Chameleon Design from Noun Project',
            'PIP' : 'Diamond by Juan Pablo Bravo from Noun Project',
            'PIT' : 'Cherry by Christian Michael Witternigg from Noun Project',
            'OHS' : 'Tic Tac Toe by Prasad from Noun Project',
            'ON' : 'on by Arthur Shlain from Noun Project',
            'OM' : 'om by Cedric Villain from Noun Project',
            'OK' : 'Ok by Liesl Kruger from Noun Project',
            'OH' : 'OH by Jolan Soens from Noun Project',
            'OF' : 'Power by Cengiz SARI from Noun Project',
            'OD' : 'e chord by Fabio Granara from Noun Project',
            'OX' : 'ox by MaJo Ox from Noun Project',
            'OW' : 'Arthritis Pain by The Present Group from Noun Project',
            'OS' : 'dead by Julien Deveaux from Noun Project',
            'OR' : 'or by Marco Olgio from Noun Project',
            'OP' : 'Gurney by Ralf Schmitzer from Noun Project',
            'GAG' : 'Gag by Luis Prado from Noun Project',
            'DEV' : 'CSS by Garrett Knoll from Noun Project',
            'DEW' : 'drop by Nithin Davis Nanthikkara from Noun Project',
            'HI' : 'Meeting by Sergi Delgado from Noun Project',
            'DEL' : 'delete file by Arthur Shlain from Noun Project',
            'HO' : 'Ghana by Amos Kofi Commey from Noun Project',
            'DEN' : 'Desk by Krisada from Noun Project',
            'DEA' : 'Magnifying Glass by David Wong from Noun Project',
            'DEB' : 'DEB File by Arthur Shlain from Noun Project',
            'HA' : 'Ha by Alfredo Hernandez from Noun Project',
            'DEE' : 'Binoculars by joe pictos from Noun Project',
            'DEF' : 'Mute by Mourad Mokrane from Noun Project',
            'HE' : 'Male by Safwan Erooth from Noun Project',
            'AME' : 'Anvil by Jason Dilworth from Noun Project',
            'AKE' : 'Wrench by Gregor Cresnar from Noun Project',
            'AMP' : 'Amp by Ben Biondo from Noun Project',
            'PBS' : 'tv news by Oliviu Stoian from Noun Project',
            'UPS' : 'ups by Jose Armando Hernandez Lopez from Noun Project',
            'TIT' : 'breast by Leszek Pietrzak from Noun Project',
            'MOE' : 'Trolley by Jose Manuel de Laa from Noun Project',
            'AVO' : 'Avocado by Amy Schwartz from Noun Project',
            'AVE' : 'Duck by Jalele from Noun Project',
            'IVY' : 'ivy by Snpr Cartman from Noun Project',
            'SUE' : 'Lawyer by Jules Dominic from Noun Project',
            'SUB' : 'Submarine by Adam  Mullin from Noun Project',
            'ACE' : 'Ace by Danil Polshin from Noun Project',
            'SUN' : 'sun from Noun Project',
            'SUM' : 'sum by Alex Auda Samora from Noun Project',
            'ACT' : 'Streaking by Luis Prado from Noun Project',
            'NEW' : 'new by Blaise Sewell from Noun Project',
            'NET' : 'net by Stanislav Cherenkov from Noun Project',
            'TEL' : 'Telephone by Pham Thi Dieu Linh from Noun Project',
            'TEN' : 'Domino by Mourad Mokrane from Noun Project',
            'TEA' : 'Tea by Andrew Cameron from Noun Project',
            'TEC' : 'Detective by Arthur Shlain from Noun Project',
            'TED' : 'Bear by Mikhail Iskandarov from Noun Project',
            'TEE' : 'Golf by aartiraghu from Noun Project',
            'TEX' : 'TEX File by Viktor Vorobyev from Noun Project',
            'TET' : 'tether by Chameleon Design from Noun Project',
            'ADS' : 'ads by Aha-Soft from Noun Project',
            'ADD' : 'add by John Chapman from Noun Project',
            'TIP' : 'Iceberg by Luis Prado from Noun Project',
            'MED' : 'virus by Monty Martin-Weber from Noun Project',
            'MEG' : 'Gear by Lucian Novosel from Noun Project',
            'MEM' : 'talking by Juan Pablo Bravo from Noun Project',
            'MEN' : 'men by iconsmind.com from Noun Project',
            'MEH' : 'meh by Rahul Anand from Noun Project',
            'BRO' : 'Cup by Design GigaSavvy from Noun Project',
            'MET' : 'meter by Vandita Malhodra from Noun Project',
            'MEW' : 'seagulls by Sergey Demushkin from Noun Project',
            'BRA' : 'Bra by Pavel N. from Noun Project',
            'TWO' : 'two by Jim Slatton from Noun Project',
            'TP' : 'Toilet Paper by Daniele Catalanotto from Noun Project',
            'TO' : 'bag by artworkbean from Noun Project',
            'EAR' : 'Ear by Yo Szczepanska from Noun Project',
            'EAT' : 'eat by Danny Chapman from Noun Project',
            'TA' : 'Keyboard by Alexis Boudal from Noun Project',
            'AA' : 'Battery by Arthur Shlain from Noun Project',
            'HOG' : 'Pig by Adam Zubin from Noun Project',
            'AB' : 'ratio by d???rmi Good from Noun Project',
            'AE' : 'File by Chameleon Design from Noun Project',
            'AD' : 'ad by Andreas WikstrOm from Noun Project',
            'AI' : 'AI by Thomas Bruck from Noun Project',
            'HOO' : 'Little Owl by Milena Zanotelli from Noun Project',
            'HOM' : 'menu by marcel grOdl from Noun Project',
            'AM' : 'sunrise by Yelena Polyakov from Noun Project',
            'AL' : 'AL by Oliviu Stoian from Noun Project',
            'HOW' : 'tutorial by Peipei Feng from Noun Project',
            'AS' : 'Hearts by Nicolas Vicent from Noun Project',
            'AR' : 'delivery truck by Mourad Mokrane from Noun Project',
            'AT' : 'At from Noun Project',
            'HOP' : 'hop by cody sprague from Noun Project',
            'AX' : 'ax by luc vega from Noun Project',
            'HOY' : 'paper cup by Pham Thi Dieu Linh from Noun Project',
            'KGB' : 'Vladimir Putin by Remi Mercier from Noun Project',
            'EOF' : 'footer by Arthur Shlain from Noun Project',
            'RYE' : 'Rye by Joao Proenca from Noun Project',
            'EON' : 'Infinity by Bohdan Burmich from Noun Project',
            'FIR' : 'Fir by Guillaume Kurkdjian from Noun Project',
            'VAN' : 'Van by Marwa Boukarim from Noun Project',
            'FIT' : 'fit by Veronica Polinedrio from Noun Project',
            'VAC' : 'Travel by Yazmin Alanis from Noun Project',
            'FIX' : 'fix by Gregor Cresnar from Noun Project',
            'PUN' : 'Raining Cats and Dogs by Aenne Brielmann from Noun Project',
            'FIG' : 'fig by Zahi Asa from Noun Project',
            'VAS' : 'Bottle by Fabio Meroni from Noun Project',
            'FIN' : 'Shark Fin by Razlan Hanafiah from Noun Project',
            'FIL' : 'Video Camera by Mario Verduzco from Noun Project',
            'LAM' : 'connected by Sergey Krivoy from Noun Project',
            'LAD' : 'boy by Rafael Farias Leao from Noun Project',
            'LAG' : 'Snail by Michael Wohlwend from Noun Project',
            'LAB' : 'lab by Bin Hur from Noun Project',
            'JO' : 'Coffee by Andrew J. Young from Noun Project',
            'LAX' : 'Lazy by Andres Arenas from Noun Project',
            'LAY' : 'Microphone by Lee Mette from Noun Project',
            'LAV' : 'Microphone by Dan Hetteix from Noun Project',
            'LAW' : 'Law by Stephen Copinger from Noun Project',
            'LAP' : 'Stopwatch by Raj Mohanlal from Noun Project',
            'ALE' : 'Beer by Zach Harris from Noun Project',
            'UVA' : 'Sunglasses by Gilad Fried from Noun Project',
            'ME' : 'Identification Badge by Housin Aziz from Noun Project',
            'MA' : 'User by Simon from Noun Project',
            'MM' : 'measure by Arthur Shlain from Noun Project',
            'MO' : 'Missouri by NUTS4BOLTS DESIGN from Noun Project',
            'MI' : 'Michigan by Leonardo Schneider from Noun Project',
            'CBS' : 'Howard Wolowitz by Luigi Di Capua from Noun Project',
            'INN' : 'Hotel by OCHA Visual Information Unit from Noun Project',
            'ALP' : 'Mountain by Lee Mette from Noun Project',
            'INK' : 'Ink by Cornelius Danger from Noun Project',
            'ING' : 'cogs by Saishraddha Malage from Noun Project',
            'MY' : 'User by Yair Cohen from Noun Project',
            'DOH' : 'Facepalm by DW from Noun Project',
            'DON' : 'label by Sergey Krivoy from Noun Project',
            'DOO' : 'christmas ornament by Milena Zanotelli from Noun Project',
            'DOM' : 'DOM by WebPlatform.org from Noun Project',
            'DOB' : 'Whisper by Benjamin Harlow from Noun Project',
            'DOC' : 'doc by 23 icons from Noun Project',
            'DOG' : 'Dog from Noun Project',
            'DOD' : 'Scrum dod by RROOK from Noun Project',
            'DOE' : 'Deer by Callum Taylor from Noun Project',
            'FA' : 'Music Note by Vectors Market from Noun Project',
            'FE' : 'Erlenmeyer Flask by Ralf Schmitzer from Noun Project',
            'DOR' : 'Scarab Beetle by Aha-Soft from Noun Project',
            'DOS' : 'terminal by Caique Lima from Noun Project',
            'DOP' : 'Water Pump by Michael Thompson from Noun Project',
            'DOW' : 'line chart by Agus Purwanto from Noun Project',
            'SMA' : 'chat by Abner Ignatius from Noun Project',
            'YO' : 'Yo by Matt Brooks from Noun Project',
            'KOA' : 'leaf by Ema Dimitrova from Noun Project',
            'JEW' : 'Jew by Y M Eneborg from Noun Project',
            'JET' : 'Jet by Ealancheliyan s from Noun Project',
            'ALL' : 'Reply by Simon Henrotte from Noun Project',
            'PUG' : 'Pug by NATAPON CHANTABUTR from Noun Project',
            'PUB' : 'pub by Daniel Turner from Noun Project',
            'PUT' : 'put by athanagore x from Noun Project',
            'ALT' : 'alt by Zlatko Najdenovski from Noun Project',
            'ALU' : 'CPU by iconsmind.com from Noun Project',
            'PUP' : 'Dog by Delsart Olivia from Noun Project',
            'ALS' : 'Ice Bucket Challenge by Matt Brooks from Noun Project',
            'PUR' : 'Cat by anbileru adaleru from Noun Project',
            'BAC' : 'Field Sobriety Test by Luis Prado from Noun Project',
            'KOI' : 'Fish by NATAPON CHANTABUTR from Noun Project',
            'BAT' : 'Bat by Christopher T. Howlett from Noun Project',
            'TOY' : 'Toy by Sergey Demushkin from Noun Project',
            'BAR' : 'Bar from Noun Project',
            'BAP' : 'Bread by Alex Bu from Noun Project',
            'YA' : 'dollar by Aldric Rodriguez Iborra from Noun Project',
            'TOP' : 'top by Christopher T. Howlett from Noun Project',
            'TOM' : 'Cat by Arthur Shlain from Noun Project',
            'TOW' : 'Station Wagon by Simon Child from Noun Project',
            'TOT' : 'Baby by Federico Mariani from Noun Project',
            'BAY' : 'Palm Tree by Simple Icons from Noun Project',
            'BAG' : 'bag by John Caserta from Noun Project',
            'BAD' : 'bad by Alexandre from Noun Project',
            'TON' : 'Weight by Charlene Chen from Noun Project',
            'ERA' : 'Time by Stepan Prokop from Noun Project',
            'BAA' : 'Sheep by Yorlmar Campos from Noun Project',
            'BAN' : 'ban by useiconic.com from Noun Project',
            'TOC' : 'chef by Dimitri Rivault from Noun Project',
            'KOR' : 'Water Bottle by Steve Morris from Noun Project',
            'TOG' : 't-shirt by Gabriele Malaspina from Noun Project',
            'BAH' : 'Blood Squirting Lizard by Cards Against Humanity from Noun Project',
            'TOE' : 'Feet by Johan H. W. Basberg from Noun Project',
            'HIP' : 'Designer by Dan Hetteix from Noun Project',
            'BAM' : 'Load by Richard Schumann from Noun Project',
            'HIT' : 'hit by Ezra Keddell from Noun Project',
            'HIV' : 'HIV by Lee Mette from Noun Project',
            'UN' : 'Cross by Kervin Markle from Noun Project',
            'TOD' : 'Tag by Chameleon Design from Noun Project',
            'HIM' : 'Wallet by Siddharth Dasari from Noun Project',
            'HIN' : 'Paper by Calvin Goodman from Noun Project',
            'STD' : 'Condom by Jamie Dickinson from Noun Project',
            'ABC' : 'arabic by Ben Markoch from Noun Project',
            'DOT' : 'dot by Alex Fuller from Noun Project',
            'HIS' : 'Male by Miso Duzek from Noun Project',
            'STY' : 'wink by hatayas from Noun Project',
            'AVA' : 'Woman by Eugen Belyakoff from Noun Project',
            'LID' : 'Coffee by Jacob Halton from Noun Project',
            'LIE' : 'Lie by Iconathon from Noun Project',
            'LIB' : 'LIB File by Arthur Shlain from Noun Project',
            'LIT' : 'lightbulb by Marek Polakovic from Noun Project',
            'LIP' : 'lip by Tugrul Peker from Noun Project',
            'LIS' : 'Fleur de Lis by Trace Lexington Byrd from Noun Project',
            'ONE' : 'One by Deivid Saenz from Noun Project',
            'EGG' : 'Egg by Edward Boatman from Noun Project',
            'RAG' : 'Rag Doll by Arancha R from Noun Project',
            'RAD' : 'Fire by Kervin Markle from Noun Project',
            'RAN' : 'anxiety by Alex Kwa from Noun Project',
            'THC' : 'Cannabis by Joey Sabey from Noun Project',
            'RAM' : 'ram by Bryn Bodayle from Noun Project',
            'RAJ' : 'heart card by Chameleon Design from Noun Project',
            'RE' : 'reload by Jeff Portaro from Noun Project',
            'RAT' : 'Rat by Gilad Fried from Noun Project',
            'WTF' : 'Human Centipede by Gregory Sujkowski from Noun Project',
            'NED' : 'Longclaw by Catherine Please from Noun Project',
            'RAY' : 'sun by Randall Barriga from Noun Project',
            'EYE' : 'Eye from Noun Project',
            'VIA' : 'data transfer by Magicon from Noun Project',
            'NIL' : 'zero by James Kindred from Noun Project',
            'VID' : 'e-learning by Gerald Wildmoser from Noun Project',
            'TYE' : 'Man by Joao Proenca from Noun Project',
            'TYG' : 'TGA File by Viktor Vorobyev from Noun Project',
            'VIN' : 'Champagne by Alex Bu from Noun Project',
            'KIS' : 'girl by Moxilla from Noun Project',
            'KAT' : 'Totoro by Kelig Le Luron from Noun Project',
            'FUR' : 'Poodle by anna Pigem from Noun Project',
            'SUP' : 'Yo by Matt Brooks from Noun Project',
            'FUG' : 'Cigarette by Magicon from Noun Project',
            'IFF' : 'IFF File by Viktor Vorobyev from Noun Project',
            'FUN' : 'Beach Ball by Tim Piper from Noun Project',
            'UGH' : 'wake up by Claire Jones from Noun Project',
            'CEL' : 'Battery by Anusha Narvekar from Noun Project',
            'KIN' : 'users by Mourad Mokrane from Noun Project',
            'END' : 'end by Tori Holtel from Noun Project',
            'WOT' : 'Tank by Alex Auda Samora from Noun Project',
            'WOW' : 'WOW by Alfredo Hernandez from Noun Project',
            'WOO' : 'woo by Alfredo Hernandez from Noun Project',
            'WON' : 'won by Agus Purwanto from Noun Project',
            'WOK' : 'Wok by Sam Marshall from Noun Project',
            'NIS' : 'shekel by Amos Meron from Noun Project',
            'NIP' : 'Apple by Magicon from Noun Project',
            'ZZZ' : 'sleep by Mayene de La Cruz from Noun Project',
            'ABS' : 'Flexible Filament by Bryan Allen from Noun Project',
            'NIT' : 'Lice by Michael Thompson from Noun Project',
            'ATE' : 'Lobster Bib by Icon Mama from Noun Project',
            'ATM' : 'ATM by Omur Uluask from Noun Project',
            'MUD' : 'Boot by Fabio Meroni from Noun Project',
            'ATT' : 'signal by Hello Many from Noun Project',
            'ISO' : 'ISO by Alfredo Hernandez from Noun Project',
            'ATS' : 'Telephone by Ilya Kolbin from Noun Project',
            'MUM' : 'Family by Tomek Woloszyn from Noun Project',
            'SEW' : 'Button by Christopher T. Howlett from Noun Project',
            'SET' : 'Directors Chair by Jeremy J Bristol from Noun Project',
            'NUT' : 'Nut by Naomi Atkinson from Noun Project',
            'SEX' : 'Sex by Miranda Dempster from Noun Project',
            'NUN' : 'Nun by David Peña B from Noun Project',
            'SEE' : 'see by Takao Umehara from Noun Project',
            'SED' : 'upper right by Riley Shaw from Noun Project',
            'SEC' : 'Time by Sergey Demushkin from Noun Project',
            'SEA' : 'Sea by hunotika from Noun Project',
            'ASK' : 'ask by athanagore x from Noun Project',
            'SEN' : 'Trash by Daniel Nochta from Noun Project',
            'ASH' : 'Pokeball by Lucian Novosel from Noun Project',
            'NUB' : 'focus by Akshay Kore from Noun Project',
            'SEI' : 'Whale by Daria Moskvina from Noun Project',
            'ASL' : 'Sign Language by Jakob Vogel from Noun Project',
            'DUH' : 'surprised by Ariel Kotzer from Noun Project',
            'DUI' : 'Field Sobriety Test by Luis Prado from Noun Project',
            'DUO' : 'people by Fission Strategy from Noun Project',
            'DUB' : 'Dub by BjOrn Andersson from Noun Project',
            'FRO' : 'Afro by Simon Child from Noun Project',
            'DUE' : 'User by Wilson Joseph from Noun Project',
            'DUG' : 'Shovel by Dima Kolchan from Noun Project',
            'IMP' : 'imp by Olesya Kozlova from Noun Project',
            'CLY' : 'coin by 23 icons from Noun Project',
            'DUP' : 'clone by Aha-Soft from Noun Project',
            'UNI' : 'education by Vicons Design from Noun Project',
            'FRY' : 'fry by Yazmin Alanis from Noun Project',
            'PDA' : 'Laptop by Arthur Shlain from Noun Project',
            'OMG' : 'omg by Mohanabrabu BM from Noun Project',
            'ZED' : 'Cup by James Zamyslianskyj from Noun Project',
            'KY' : 'Kentucky by NUTS4BOLTS DESIGN from Noun Project',
            'ITS' : 'Traffic Light by Anna Wingard from Noun Project',
            'DO' : 'do by athanagore x from Noun Project',
            'DL' : 'Download by Marek Polakovic from Noun Project',
            'AAA' : 'Battery by Ryan Dell from Noun Project',
            'DE' : 'Venus De Milo by Nuno Lezon from Noun Project',
            'FEE' : 'Tag by Stephen JB Thomas from Noun Project',
            'MIX' : 'mix by Creative Stall from Noun Project',
            'BIN' : 'bin by Quan Do from Noun Project',
            'BIO' : 'bio by Eugene Dobrik from Noun Project',
            'BIG' : 'Zoom by Ben Rex Furneaux from Noun Project',
            'GYM' : 'Gym by Sathish Selladurai from Noun Project',
            'CUP' : 'Cup by Brandon Hopkins from Noun Project',
            'BIB' : 'Bib by David Lopez from Noun Project',
            'BIZ' : 'employees by Yazmin Alanis from Noun Project',
            'GYP' : 'Shuffle by Universal Icons from Noun Project',
            'BIT' : 'Ice Cream by Lucas Rod from Noun Project',
            'GOO' : 'blob by Ryan Speziale from Noun Project',
            'SLY' : 'sly by Lemon Liu from Noun Project',
            'GOD' : 'Atlas by Jakob Vogel from Noun Project',
            'GOA' : 'Drink by Siddharth Dasari from Noun Project',
            'GOB' : 'Man by Eugen Belyakoff from Noun Project',
            'GOT' : 'Longclaw by Catherine Please from Noun Project',
            'FET' : 'N-channel Fet by Lloyd Humphreys from Noun Project',
            'FES' : 'Fez by Edaimon De Juan from Noun Project',
            'WO' : 'agile by Nimal Raj from Noun Project',
            'RIP' : 'rip by Richard Cordero from Noun Project',
            'RIM' : 'rim by Paulo Sa Ferreira from Noun Project',
            'RIG' : 'Truck by Luis Prado from Noun Project',
            'RID' : 'Horse by Dream Icons from Noun Project',
            'RIB' : 'pork by James Keuning from Noun Project',
            'HAH' : 'Rain wind by Pham Thi Dieu Linh from Noun Project',
            'HAM' : 'Ham by jon trillana from Noun Project',
            'HAN' : 'Carbonite by Andrew Forrester from Noun Project',
            'BUM' : 'Hobo by Luis Prado from Noun Project',
            'HAG' : 'Witch by Nicolas Vicent from Noun Project',
            'HAY' : 'hay by Anuar Zhumaev from Noun Project',
            'HAP' : 'lego by Giuditta Valentina Gentile from Noun Project',
            'GPU' : 'Microchip by Alex Tai from Noun Project',
            'THE' : 'Coffee by Federico Panzano from Noun Project',
            'HAS' : 'flash by Prasad from Noun Project',
            'HAT' : 'hat by Dara Ullrich from Noun Project',
            'YEH' : 'business group by Gregor Cresnar from Noun Project',
            'SYE' : 'Dentist by Bhasker Sharma from Noun Project',
            'YEN' : 'yen by riyazali from Noun Project',
            'YEA' : 'Check Circle by Michael Bundscherer from Noun Project',
            'KIP' : 'Kip by Agus Purwanto from Noun Project',
            'KIT' : 'kit by Maurizio Fusillo from Noun Project',
            'KIK' : 'Low Tide by Pham Thi Dieu Linh from Noun Project',
            'NIX' : 'Nix by Denis Moskowitz from Noun Project',
            'GEM' : 'gem by Javier Calvo Patiño from Noun Project',
            'WIN' : 'win by Julia Stoffer from Noun Project',
            'YEP' : 'select by Sergey Demushkin from Noun Project',
            'YES' : 'yes by iconsmind.com from Noun Project',
            'YEW' : 'Plant by Aaron P. Brown from Noun Project',
            'KID' : 'Kid by Rodrigo alvarez Virgós from Noun Project',
            'FDA' : 'Cow by Aha-Soft from Noun Project',
            'EMO' : 'emo by Thomas Helbig from Noun Project',
            'CRY' : 'cry by James Bickerton from Noun Project',
            'EMU' : 'Emu by N.K.Narasimhan from Noun Project',
            'EMS' : 'Ambulance by Mourad Mokrane from Noun Project',
            'PS' : 'Ps by Alfredo Hernandez from Noun Project',
            'PA' : 'Speaker by Yair Cohen from Noun Project',
            'PE' : 'Basketball by Geoffrey Joe from Noun Project',
            'PI' : 'P.I. by Mister Pixel from Noun Project',
            'FOR' : 'Drizzle by Ashwin Dinesh from Noun Project',
            'EFT' : 'mobile payment by Alfredo Hernandez from Noun Project',
            'FOX' : 'Fox by Sebastian Blei from Noun Project',
            'FOE' : 'separation by Arthur Shlain from Noun Project',
            'FOG' : 'fog by Adam Whitcroft from Noun Project',
            'FOB' : 'Foot Over Bridge by Vineet Kumar Thakur from Noun Project',
            'FON' : 'FON File by Arthur Shlain from Noun Project',
            'OPT' : 'Share by Casper Jensen from Noun Project',
            'WWW' : 'www by Souvik Bhattacharjee from Noun Project',
            'OPS' : 'sad shield by Marek Polakovic from Noun Project',
            'OPE' : 'Corridor by Gilbert Bages from Noun Project',
            'LCD' : 'LCD by Agus Purwanto from Noun Project',
            'JOY' : 'joy by WARPAINT Media Inc. from Noun Project',
            'COP' : 'cop by Nathan Stang from Noun Project',
            'COS' : 'cos by Chameleon Design from Noun Project',
            'COT' : 'cot by anbileru adaleru from Noun Project',
            'COW' : 'Cow by Alessandro Costa from Noun Project',
            'COY' : 'flirty by James Kindred from Noun Project',
            'ILL' : 'Cover Mouth by Alejandro Santander from Noun Project',
            'PEW' : 'pew by Ivan Chernykh from Noun Project',
            'PEP' : 'Battery by Vicons Design from Noun Project',
            'CIA' : 'CIA by Luke Anthony Firth from Noun Project',
            'PER' : 'Computer Calculator by Yorlmar Campos from Noun Project',
            'PES' : 'NES by Jack from Noun Project',
            'PEN' : 'Pen by Ethan Clark from Noun Project',
            'COB' : 'Corn by Terri Toombs from Noun Project',
            'COD' : 'cod by Andres Magnusson from Noun Project',
            'COG' : 'cog by useiconic.com from Noun Project',
            'PED' : 'Walk by Nike Jenny Bruinsma from Noun Project',
            'PEE' : 'Urinal by Bohdan Burmich from Noun Project',
            'PEG' : 'Pegleg by Javier Sanchez from Noun Project',
            'COL' : 'Text Columns by Arthur Shlain from Noun Project',
            'CON' : 'Scale by Veronika Karenina from Noun Project',
            'OLD' : 'old by Igor Yanovsky from Noun Project',
            'OLE' : 'MSI File by Viktor Vorobyev from Noun Project',
            'RAW' : 'raw by Thomas Helbig from Noun Project',
            'JOB' : 'job by Mohamad Sabbagh from Noun Project',
            'JOE' : 'Coffee by Tom Glass, Jr. from Noun Project',
            'WAN' : 'Wireless Router by Jaime Carrion from Noun Project',
            'RAP' : 'Radio by Toni Valdes Medina from Noun Project',
            'WAG' : 'Dog by Ariel Kotzer from Noun Project',
            'WAD' : 'Money by Luis Prado from Noun Project',
            'WAY' : 'Tracking Location by Friedrich Santana from Noun Project',
            'WAX' : 'Wax by Yaroslav Samoilov from Noun Project',
            'WAT' : 'Angkor Wat by Stefan Spieler from Noun Project',
            'WAR' : 'War by nayeli zimmermann from Noun Project',
            'PLU' : 'Add User by Wilson Joseph from Noun Project',
            'RUN' : 'run by Claire Jones from Noun Project',
            'UFO' : 'ufo by Simon Child from Noun Project',
            'RUB' : 'rub by 23 icons from Noun Project',
            'PRY' : 'Crowbar by Andreas Bjurenborg from Noun Project',
            'RUG' : 'rug by iconoci from Noun Project',
            'PLY' : 'Leaflet by Francesco Cesqo Stefanini from Noun Project',
            'DIM' : 'brightness by John Caserta from Noun Project',
            'DID' : 'Boots by lastspark from Noun Project',
            'DIE' : 'die by athanagore x from Noun Project',
            'DIG' : 'Shovel by Scott Lewis from Noun Project',
            'AIS' : 'Radar by Marc Fouque from Noun Project',
            'AIR' : 'Air by Renee Ramsey-Passmore from Noun Project',
            'AIM' : 'aim by Creative Stall from Noun Project',
            'AIL' : 'Garlic by Creative Stall from Noun Project',
            'DIY' : 'Reprap by Arthur Schmitt from Noun Project',
            'DIT' : 'Pen by iconsmind.com from Noun Project',
            'AID' : 'aid by Fission Strategy from Noun Project',
            'DIV' : 'DIV by Iris Li from Noun Project',
            'DIP' : 'dip by Claire Jones from Noun Project',
            'DIS' : 'Chicken by Tatiana from Noun Project',
            'SOB' : 'cry by Lemon Liu from Noun Project',
            'ZIP' : 'Zip by iconoci from Noun Project',
            'GAY' : 'Gay by Maurizio Fusillo from Noun Project',
            'NSA' : 'Eye by Pierre Orsander from Noun Project',
            'GAT' : 'gat by Yun Jeong Hong from Noun Project',
            'GAS' : 'Gas from Noun Project',
            'SOL' : 'sun by Ashley van Dyck from Noun Project',
            'SON' : 'son by Snehal Patil from Noun Project',
            'SOP' : 'bribe by Luis Prado from Noun Project',
            'SOS' : 'SOS by Stefano Vetere from Noun Project',
            'GAL' : 'girl by matthijs de block from Noun Project',
            'SOT' : 'jug by Vandita Malhodra from Noun Project',
            'SOW' : 'Plant by Michele Zamparo from Noun Project',
            'CHI' : 'meditation by Jens Tarning from Noun Project',
            'SOY' : 'soy by factor[e] design initiative from Noun Project',
            'SOX' : 'Sock by Eugen Belyakoff from Noun Project',
            'GAB' : 'Speech Bubble by Krish from Noun Project',
            'IS' : 'sledge hammer by Jason Dilworth from Noun Project',
            'IRS' : 'Uncle Sam by Luis Prado from Noun Project',
            'IT' : 'IT by Nattanicha Klaikham from Noun Project',
            'IRK' : 'Tattoo Needles by Paulina Jadeszko from Noun Project',
            'IN' : 'In by James Keuning from Noun Project',
            'IRA' : 'Bank by anbileru adaleru from Noun Project',
            'IC' : 'Microchip by Martin Vanco from Noun Project',
            'IRE' : 'angry by Rikki Lorie from Noun Project',
            'IF' : 'condition by Arthur Shlain from Noun Project',
            'ART' : 'Art by anson nguyen from Noun Project',
            'ARC' : 'arc by Dilon Choudhury from Noun Project',
            'ARD' : 'playing card by anbileru adaleru from Noun Project',
            'ARE' : 'You Are Here by Maico Amorim from Noun Project',
            'PPL' : 'guy by Tommy Lau from Noun Project',
            'ARK' : 'ark by Yorlmar Campos from Noun Project',
            'ARM' : 'arm by Deivid Saenz from Noun Project',
            'BOX' : 'Box by Martin Karachorov from Noun Project',
            'BOY' : 'boy by Mike Ashley from Noun Project',
            'TIX' : 'Ticket by Dani Rolli from Noun Project',
            'NAG' : 'Tattoo Needles by Paulina Jadeszko from Noun Project',
            'BC' : 'birth control by Michelle Parent from Noun Project',
            'BOP' : 'explosion by Nick Abrams from Noun Project',
            'NAH' : 'down arrow by Tim Neumann from Noun Project',
            'BO' : 'Lightning by Pham Thi Dieu Linh from Noun Project',
            'BOT' : 'Robot by Mateus Leal from Noun Project',
            'BOW' : 'bow by Yuko Iwai from Noun Project',
            'NAS' : 'NAS by Yazmin Alanis from Noun Project',
            'NAP' : 'Bunk Bed by Jose Luis Algara from Noun Project',
            'BON' : 'Mum Emoji by Mohanabrabu BM from Noun Project',
            'BOO' : 'boo by Oliviu Stoian from Noun Project',
            'BOA' : 'Snake by heathersabrina from Noun Project',
            'BOB' : 'bob by Stefania Bonacasa from Noun Project',
            'NAY' : 'Remove by Hello Many from Noun Project',
            'BY' : 'talking by Samy Menai from Noun Project',
            'BOG' : 'typha by Viktor Fedyuk from Noun Project',
            'PET' : 'Pet by Cristiano Zoucas from Noun Project',
            'SQL' : 'database by Richard Schumann from Noun Project',
            'FLY' : 'fly by Felipe Perucho from Noun Project',
            'FLU' : 'epidemic by OCHA Visual Information Unit from Noun Project',
            'EEL' : 'eel by Guillem  Lopez Gurrera from Noun Project',
            'HOE' : 'hoe by factor[e] design initiative from Noun Project',
            'HOB' : 'Oven by Arthur Shlain from Noun Project',
            'ROK' : 'ROK Espresso by Eric M. Ellis from Noun Project',
            'ROM' : 'Royal Ontario Museum by Maziar from Noun Project',
            'ROO' : 'Kangaroo by Nike Jenny Bruinsma from Noun Project',
            'ROB' : 'Burglar by Designvad from Noun Project',
            'ROC' : 'Taiwan by Albert Huang from Noun Project',
            'ROD' : 'rod by BraveBros. from Noun Project',
            'ROE' : 'Sushi by Stephanie Wauters from Noun Project',
            'PEA' : 'pea by Ji Sub Jeong from Noun Project',
            'ROT' : 'flies by Marie Van den Broeck from Noun Project',
            'ROW' : 'Chairs by Sebastian Langer from Noun Project',
            'EWE' : 'rapper by Amos Kofi Commey from Noun Project',
            'TRY' : 'Try by Marco Olgio from Noun Project',
            'VOL' : 'Volume by NAS from Noun Project',
            'UT' : 'Utah by NUTS4BOLTS DESIGN from Noun Project',
            'HOT' : 'Hot by Dmitry Baranovskiy from Noun Project',
            'US' : 'Virginia by Claire Jones from Noun Project',
            'VOW' : 'Marriage Proposal by Luis Prado from Noun Project',
            'VOX' : 'Sliders by sagit milshtein from Noun Project',
            'IDS' : 'Wallet by Ollie Khakwani from Noun Project',
            'IDE' : 'code by Nikhil Dev from Noun Project',
            'AHA' : 'snap by chris dawson from Noun Project',
            'NM' : 'New Mexico by NUTS4BOLTS DESIGN from Noun Project',
            'NO' : 'No from Noun Project',
            'NA' : 'by Gustavo Aoyagi from Noun Project',
            'NE' : 'Nebraska by NUTS4BOLTS DESIGN from Noun Project',
            'UEY' : 'Arrow by Nikita Kozin from Noun Project',
            'NS' : 'Train by jaap from Noun Project',
            'ODD' : 'odd by JMA from Noun Project',
            'ODE' : 'phonograph by Becca from Noun Project',
            'ELK' : 'elk by Darrin Higgins from Noun Project',
            'FED' : 'Police by Luis Prado from Noun Project',
            'CUT' : 'Cut by Nathan Thomson from Noun Project',
            'CUR' : 'Euro by Patrick Trouve from Noun Project',
            'ELM' : 'Tree by Rishad Patel from Noun Project',
            'FEN' : 'Shuttlecock by Nikhil Singhal from Noun Project',
            'ELF' : 'Elf by Leslie Ranchon from Noun Project',
            'FEW' : 'It\'s Smaller by Dustin\'s Words from Noun Project',
            'CUE' : 'Pool Table by Nathan Thomson from Noun Project',
            'CUB' : 'Bear by m. turan ercan from Noun Project',
            'CUM' : 'Sperm by Aha-Soft from Noun Project',
            'FEZ' : 'Fez by Henry Ryder from Noun Project',
            'WIG' : 'Wig by Stephen Copinger from Noun Project',
            'LED' : 'LED by jon trillana from Noun Project',
            'LEE' : 'bruce lee by Pavel from Noun Project',
            'LEG' : 'leg by Brian Gonzalez from Noun Project',
            'LEI' : 'garland by Gabriella Fono from Noun Project',
            'LEK' : 'mobile payment by Adam  Mullin from Noun Project',
            'WIT' : 'nerd by Ivan Colic from Noun Project',
            'LET' : 'Arrow by Alex S. Lakas from Noun Project',
            'LEV' : 'Lion by Aha-Soft from Noun Project',
            'LEW' : 'Lion by Aha-Soft from Noun Project',
            'LEX' : 'Law by Arthur Shlain from Noun Project',
            'FBI' : 'spy by Dan Hetteix from Noun Project',
            'WIZ' : 'Magic Wand by Sergey Demushkin from Noun Project',
            'USE' : 'Wash by Klara Zalokar from Noun Project',
            'CIG' : 'Electronic Cigarette by Straw Dog Design from Noun Project',
            'USA' : 'USA by Matthieu Rodrigues from Noun Project',
            'DAD' : 'dad by Tomek Woloszyn from Noun Project',
            'DAB' : 'towels by Fernando Affonso from Noun Project',
            'DAM' : 'Dam from Noun Project',
            'DAW' : 'Crossfade by Miguel Angel Martinez from Noun Project',
            'DAP' : 'Fist Bump by Kyle Tezak from Noun Project',
            'DAY' : 'day by Maurizio Fusillo from Noun Project',
            'ICE' : 'Ice by Ates Evren Aydinel from Noun Project',
            'ICY' : 'ice cubes by Dolly Vu from Noun Project',
            'EGO' : 'Self Obsession by Michael A. Salter from Noun Project',
            'TOO' : 'T Square by Creative Stall from Noun Project',
            'OOF' : 'coin by 23 icons from Noun Project',
            'OOH' : 'surprised by Herbert Spencer from Noun Project',}

def main():
    import time
    import requests
    from requests_oauthlib import OAuth1
    import urllib
    import os

    key = os.environ.get('THENOUNPROJECTKEY', 'mydefaultkey')
    secret = os.environ.get('THENOUNPROJECTSECRET', 'mydefaultsecret')
    auth = OAuth1(key, secret)

    from names import badNames
    namelist = badNames()
    print namelist

    # Open a file
    f = open('attrib.txt', 'w')
    for i in namelist.keys():
        endpoint = "http://api.thenounproject.com/icon/" + i
        print endpoint
        r = requests.get(endpoint, auth=auth)

        if r.status_code == 200:
            remoteFilename=r.json().get('icon').get('preview_url')
            print remoteFilename
            urllib.urlretrieve(remoteFilename, filename='images\\'+i+".png")

            attrib=r.json().get('icon').get('attribution')
            line = "'" + i + "'" + " : '" + attrib + "'"
            f.write(line.encode('utf8'))
        else:
            print "none"
        time.sleep(1)
    print "end"
    f.close()

if __name__ == "__main__":
    main()
else:
    print("import into another module")
